### ISSUE TITLE
feature: post, get요청을 담당하는 router를 개발한다.

### ISSUE THREAD

**Issue by chc216** [tmdwo5825-naver-com/BE-CBNU-Mr.CAT_MOM#11]
## 📌 상세 내용
&nbsp; - p
post, get요청을 담당하는 router개발

<br/><br/>
## 🌠 구현 내용(post router)
- [x] 파일을 s3에 업로드하고 url을 받아와 메타데이터와 함께 데이터베이스에 저장하는 router개발

  
## 🌠 구현 내용(get router)
- [x] 루트 경로 엔드포인트에 get요청이 들어오면 자동으로 데이터베이스의 모든 레코드를 반환하는 router개발

**Comment by Bangseungjae** [comment]
멋지다.
